<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chain.proto

namespace Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>protocol.AssetStore</code>
 */
class AssetStore extends \Google\Protobuf\Internal\Message
{
    /**
     *required
     *
     * Generated from protobuf field <code>.protocol.AssetKey key = 1;</code>
     */
    private $key = null;
    /**
     * Generated from protobuf field <code>int64 amount = 2;</code>
     */
    private $amount = 0;
    /**
     * Generated from protobuf field <code>.protocol.AssetProperty property = 3;</code>
     */
    private $property = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Protocol\AssetKey $key
     *          required
     *     @type int|string $amount
     *     @type \Protocol\AssetProperty $property
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Chain::initOnce();
        parent::__construct($data);
    }

    /**
     *required
     *
     * Generated from protobuf field <code>.protocol.AssetKey key = 1;</code>
     * @return \Protocol\AssetKey
     */
    public function getKey()
    {
        return $this->key;
    }

    /**
     *required
     *
     * Generated from protobuf field <code>.protocol.AssetKey key = 1;</code>
     * @param \Protocol\AssetKey $var
     * @return $this
     */
    public function setKey($var)
    {
        GPBUtil::checkMessage($var, \Protocol\AssetKey::class);
        $this->key = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 amount = 2;</code>
     * @return int|string
     */
    public function getAmount()
    {
        return $this->amount;
    }

    /**
     * Generated from protobuf field <code>int64 amount = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setAmount($var)
    {
        GPBUtil::checkInt64($var);
        $this->amount = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.protocol.AssetProperty property = 3;</code>
     * @return \Protocol\AssetProperty
     */
    public function getProperty()
    {
        return $this->property;
    }

    /**
     * Generated from protobuf field <code>.protocol.AssetProperty property = 3;</code>
     * @param \Protocol\AssetProperty $var
     * @return $this
     */
    public function setProperty($var)
    {
        GPBUtil::checkMessage($var, \Protocol\AssetProperty::class);
        $this->property = $var;

        return $this;
    }

}

