<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chain.proto

namespace Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>protocol.AssetProperty</code>
 */
class AssetProperty extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 decimal = 1;</code>
     */
    private $decimal = 0;
    /**
     * Generated from protobuf field <code>string description = 2;</code>
     */
    private $description = '';
    /**
     * Generated from protobuf field <code>int64 max_supply = 3;</code>
     */
    private $max_supply = 0;
    /**
     * Generated from protobuf field <code>int64 issued_amount = 4;</code>
     */
    private $issued_amount = 0;
    /**
     * Generated from protobuf field <code>int32 fee_percent = 5;</code>
     */
    private $fee_percent = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $decimal
     *     @type string $description
     *     @type int|string $max_supply
     *     @type int|string $issued_amount
     *     @type int $fee_percent
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Chain::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 decimal = 1;</code>
     * @return int
     */
    public function getDecimal()
    {
        return $this->decimal;
    }

    /**
     * Generated from protobuf field <code>int32 decimal = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setDecimal($var)
    {
        GPBUtil::checkInt32($var);
        $this->decimal = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string description = 2;</code>
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Generated from protobuf field <code>string description = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->description = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 max_supply = 3;</code>
     * @return int|string
     */
    public function getMaxSupply()
    {
        return $this->max_supply;
    }

    /**
     * Generated from protobuf field <code>int64 max_supply = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMaxSupply($var)
    {
        GPBUtil::checkInt64($var);
        $this->max_supply = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 issued_amount = 4;</code>
     * @return int|string
     */
    public function getIssuedAmount()
    {
        return $this->issued_amount;
    }

    /**
     * Generated from protobuf field <code>int64 issued_amount = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setIssuedAmount($var)
    {
        GPBUtil::checkInt64($var);
        $this->issued_amount = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 fee_percent = 5;</code>
     * @return int
     */
    public function getFeePercent()
    {
        return $this->fee_percent;
    }

    /**
     * Generated from protobuf field <code>int32 fee_percent = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setFeePercent($var)
    {
        GPBUtil::checkInt32($var);
        $this->fee_percent = $var;

        return $this;
    }

}

