<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: overlay.proto

namespace Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *register notification events
 *
 * Generated from protobuf message <code>protocol.ChainHello</code>
 */
class ChainHello extends \Google\Protobuf\Internal\Message
{
    /**
     *default enable all apis
     *
     * Generated from protobuf field <code>repeated .protocol.ChainMessageType api_list = 1;</code>
     */
    private $api_list;
    /**
     * Generated from protobuf field <code>int64 timestamp = 2;</code>
     */
    private $timestamp = 0;

    public function __construct() {
        \GPBMetadata\Overlay::initOnce();
        parent::__construct();
    }

    /**
     *default enable all apis
     *
     * Generated from protobuf field <code>repeated .protocol.ChainMessageType api_list = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getApiList()
    {
        return $this->api_list;
    }

    /**
     *default enable all apis
     *
     * Generated from protobuf field <code>repeated .protocol.ChainMessageType api_list = 1;</code>
     * @param int[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setApiList($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::ENUM, \Protocol\ChainMessageType::class);
        $this->api_list = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 timestamp = 2;</code>
     * @return int|string
     */
    public function getTimestamp()
    {
        return $this->timestamp;
    }

    /**
     * Generated from protobuf field <code>int64 timestamp = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTimestamp($var)
    {
        GPBUtil::checkInt64($var);
        $this->timestamp = $var;

        return $this;
    }

}

