<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: overlay.proto

namespace Protocol;

/**
 * Protobuf enum <code>Protocol\ChainTxStatus\TxStatus</code>
 */
class ChainTxStatus_TxStatus
{
    /**
     * Generated from protobuf enum <code>UNDEFINED = 0;</code>
     */
    const UNDEFINED = 0;
    /**
     * web server will check tx paramters, signatures etc fist, noitfy CONFIRMED if pass
     *
     * Generated from protobuf enum <code>CONFIRMED = 1;</code>
     */
    const CONFIRMED = 1;
    /**
     * master will check futher before put it into pending queue
     *
     * Generated from protobuf enum <code>PENDING = 2;</code>
     */
    const PENDING = 2;
    /**
     * notify if Tx write ledger successfully
     *
     * Generated from protobuf enum <code>COMPLETE = 3;</code>
     */
    const COMPLETE = 3;
    /**
     * notify once failure and set error_code
     *
     * Generated from protobuf enum <code>FAILURE = 4;</code>
     */
    const FAILURE = 4;
}

