<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: overlay.proto

namespace Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>protocol.ChainPeerMessage</code>
 */
class ChainPeerMessage extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string src_peer_addr = 1;</code>
     */
    private $src_peer_addr = '';
    /**
     * Generated from protobuf field <code>repeated string des_peer_addrs = 2;</code>
     */
    private $des_peer_addrs;
    /**
     * Generated from protobuf field <code>bytes data = 3;</code>
     */
    private $data = '';

    public function __construct() {
        \GPBMetadata\Overlay::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>string src_peer_addr = 1;</code>
     * @return string
     */
    public function getSrcPeerAddr()
    {
        return $this->src_peer_addr;
    }

    /**
     * Generated from protobuf field <code>string src_peer_addr = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setSrcPeerAddr($var)
    {
        GPBUtil::checkString($var, True);
        $this->src_peer_addr = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string des_peer_addrs = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getDesPeerAddrs()
    {
        return $this->des_peer_addrs;
    }

    /**
     * Generated from protobuf field <code>repeated string des_peer_addrs = 2;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setDesPeerAddrs($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->des_peer_addrs = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes data = 3;</code>
     * @return string
     */
    public function getData()
    {
        return $this->data;
    }

    /**
     * Generated from protobuf field <code>bytes data = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setData($var)
    {
        GPBUtil::checkString($var, False);
        $this->data = $var;

        return $this;
    }

}

