<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common.proto

namespace Protocol;

/**
 * Protobuf enum <code>Protocol\ERRORCODE</code>
 */
class ERRORCODE
{
    /**
     * Generated from protobuf enum <code>ERRCODE_SUCCESS = 0;</code>
     */
    const ERRCODE_SUCCESS = 0;
    /**
     * Generated from protobuf enum <code>ERRCODE_INTERNAL_ERROR = 1;</code>
     */
    const ERRCODE_INTERNAL_ERROR = 1;
    /**
     * Generated from protobuf enum <code>ERRCODE_INVALID_PARAMETER = 2;</code>
     */
    const ERRCODE_INVALID_PARAMETER = 2;
    /**
     * Generated from protobuf enum <code>ERRCODE_ALREADY_EXIST = 3;</code>
     */
    const ERRCODE_ALREADY_EXIST = 3;
    /**
     * Generated from protobuf enum <code>ERRCODE_NOT_EXIST = 4;</code>
     */
    const ERRCODE_NOT_EXIST = 4;
    /**
     * Generated from protobuf enum <code>ERRCODE_TX_TIMEOUT = 5;</code>
     */
    const ERRCODE_TX_TIMEOUT = 5;
    /**
     * Generated from protobuf enum <code>ERRCODE_ACCESS_DENIED = 6;</code>
     */
    const ERRCODE_ACCESS_DENIED = 6;
    /**
     * Generated from protobuf enum <code>ERRCODE_MATH_OVERFLOW = 7;</code>
     */
    const ERRCODE_MATH_OVERFLOW = 7;
    /**
     * Generated from protobuf enum <code>ERRCODE_EXPR_CONDITION_RESULT_FALSE = 20;</code>
     */
    const ERRCODE_EXPR_CONDITION_RESULT_FALSE = 20;
    /**
     * Generated from protobuf enum <code>ERRCODE_EXPR_CONDITION_SYNTAX_ERROR = 21;</code>
     */
    const ERRCODE_EXPR_CONDITION_SYNTAX_ERROR = 21;
    /**
     * UNUSED
     *
     * Generated from protobuf enum <code>ERRCODE_INVALID_PUBKEY = 90;</code>
     */
    const ERRCODE_INVALID_PUBKEY = 90;
    /**
     * Generated from protobuf enum <code>ERRCODE_INVALID_PRIKEY = 91;</code>
     */
    const ERRCODE_INVALID_PRIKEY = 91;
    /**
     * Generated from protobuf enum <code>ERRCODE_ASSET_INVALID = 92;</code>
     */
    const ERRCODE_ASSET_INVALID = 92;
    /**
     * Generated from protobuf enum <code>ERRCODE_INVALID_SIGNATURE = 93;</code>
     */
    const ERRCODE_INVALID_SIGNATURE = 93;
    /**
     * Generated from protobuf enum <code>ERRCODE_INVALID_ADDRESS = 94;</code>
     */
    const ERRCODE_INVALID_ADDRESS = 94;
    /**
     * Generated from protobuf enum <code>ERRCODE_MISSING_OPERATIONS = 97;</code>
     */
    const ERRCODE_MISSING_OPERATIONS = 97;
    /**
     * Generated from protobuf enum <code>ERRCODE_TOO_MANY_OPERATIONS = 98;</code>
     */
    const ERRCODE_TOO_MANY_OPERATIONS = 98;
    /**
     * Generated from protobuf enum <code>ERRCODE_BAD_SEQUENCE = 99;</code>
     */
    const ERRCODE_BAD_SEQUENCE = 99;
    /**
     *PHANTOM LOW RESERVE
     *
     * Generated from protobuf enum <code>ERRCODE_ACCOUNT_LOW_RESERVE = 100;</code>
     */
    const ERRCODE_ACCOUNT_LOW_RESERVE = 100;
    /**
     * Generated from protobuf enum <code>ERRCODE_ACCOUNT_SOURCEDEST_EQUAL = 101;</code>
     */
    const ERRCODE_ACCOUNT_SOURCEDEST_EQUAL = 101;
    /**
     * Generated from protobuf enum <code>ERRCODE_ACCOUNT_DEST_EXIST = 102;</code>
     */
    const ERRCODE_ACCOUNT_DEST_EXIST = 102;
    /**
     * Generated from protobuf enum <code>ERRCODE_ACCOUNT_NOT_EXIST = 103;</code>
     */
    const ERRCODE_ACCOUNT_NOT_EXIST = 103;
    /**
     *IOU LOW RESERVE
     *
     * Generated from protobuf enum <code>ERRCODE_ACCOUNT_ASSET_LOW_RESERVE = 104;</code>
     */
    const ERRCODE_ACCOUNT_ASSET_LOW_RESERVE = 104;
    /**
     * Generated from protobuf enum <code>ERRCODE_ACCOUNT_ASSET_AMOUNT_TOO_LARGE = 105;</code>
     */
    const ERRCODE_ACCOUNT_ASSET_AMOUNT_TOO_LARGE = 105;
    /**
     * Generated from protobuf enum <code>ERRCODE_ACCOUNT_INIT_LOW_RESERVE = 106;</code>
     */
    const ERRCODE_ACCOUNT_INIT_LOW_RESERVE = 106;
    /**
     * Generated from protobuf enum <code>ERRCODE_FEE_NOT_ENOUGH = 111;</code>
     */
    const ERRCODE_FEE_NOT_ENOUGH = 111;
    /**
     * Generated from protobuf enum <code>ERRCODE_FEE_INVALID = 112;</code>
     */
    const ERRCODE_FEE_INVALID = 112;
    /**
     * Generated from protobuf enum <code>ERRCODE_OUT_OF_TXCACHE = 114;</code>
     */
    const ERRCODE_OUT_OF_TXCACHE = 114;
    /**
     * Generated from protobuf enum <code>ERRCODE_WEIGHT_NOT_VALID = 120;</code>
     */
    const ERRCODE_WEIGHT_NOT_VALID = 120;
    /**
     * Generated from protobuf enum <code>ERRCODE_THRESHOLD_NOT_VALID = 121;</code>
     */
    const ERRCODE_THRESHOLD_NOT_VALID = 121;
    /**
     *metadata version error
     *
     * Generated from protobuf enum <code>ERRCODE_INVALID_DATAVERSION = 144;</code>
     */
    const ERRCODE_INVALID_DATAVERSION = 144;
    /**
     * Generated from protobuf enum <code>ERRCODE_TX_SIZE_TOO_BIG = 146;</code>
     */
    const ERRCODE_TX_SIZE_TOO_BIG = 146;
    /**
     * Generated from protobuf enum <code>ERRCODE_CONTRACT_EXECUTE_FAIL = 151;</code>
     */
    const ERRCODE_CONTRACT_EXECUTE_FAIL = 151;
    /**
     * Generated from protobuf enum <code>ERRCODE_CONTRACT_SYNTAX_ERROR = 152;</code>
     */
    const ERRCODE_CONTRACT_SYNTAX_ERROR = 152;
    /**
     * Generated from protobuf enum <code>ERRCODE_CONTRACT_TOO_MANY_RECURSION = 153;</code>
     */
    const ERRCODE_CONTRACT_TOO_MANY_RECURSION = 153;
    /**
     * Generated from protobuf enum <code>ERRCODE_CONTRACT_TOO_MANY_TRANSACTIONS = 154;</code>
     */
    const ERRCODE_CONTRACT_TOO_MANY_TRANSACTIONS = 154;
    /**
     * Generated from protobuf enum <code>ERRCODE_CONTRACT_EXECUTE_EXPIRED = 155;</code>
     */
    const ERRCODE_CONTRACT_EXECUTE_EXPIRED = 155;
    /**
     * Generated from protobuf enum <code>ERRCODE_TX_INSERT_QUEUE_FAIL = 160;</code>
     */
    const ERRCODE_TX_INSERT_QUEUE_FAIL = 160;
}

