<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: consensus.proto

namespace Protocol;

/**
 * Protobuf enum <code>Protocol\FeeConfig\Type</code>
 */
class FeeConfig_Type
{
    /**
     * Generated from protobuf enum <code>UNKNOWN = 0;</code>
     */
    const UNKNOWN = 0;
    /**
     * Generated from protobuf enum <code>GAS_PRICE = 1;</code>
     */
    const GAS_PRICE = 1;
    /**
     * Generated from protobuf enum <code>BASE_RESERVE = 2;</code>
     */
    const BASE_RESERVE = 2;
}

