<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: consensus.proto

namespace Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>protocol.FeeConfig</code>
 */
class FeeConfig extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 gas_price = 1;</code>
     */
    private $gas_price = 0;
    /**
     * Generated from protobuf field <code>int64 base_reserve = 2;</code>
     */
    private $base_reserve = 0;

    public function __construct() {
        \GPBMetadata\Consensus::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>int64 gas_price = 1;</code>
     * @return int|string
     */
    public function getGasPrice()
    {
        return $this->gas_price;
    }

    /**
     * Generated from protobuf field <code>int64 gas_price = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setGasPrice($var)
    {
        GPBUtil::checkInt64($var);
        $this->gas_price = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 base_reserve = 2;</code>
     * @return int|string
     */
    public function getBaseReserve()
    {
        return $this->base_reserve;
    }

    /**
     * Generated from protobuf field <code>int64 base_reserve = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setBaseReserve($var)
    {
        GPBUtil::checkInt64($var);
        $this->base_reserve = $var;

        return $this;
    }

}

