<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: overlay.proto

namespace Protocol;

/**
 * Protobuf enum <code>Protocol\Ledgers\SyncCode</code>
 */
class Ledgers_SyncCode
{
    /**
     *成功
     *
     * Generated from protobuf enum <code>OK = 0;</code>
     */
    const OK = 0;
    /**
     *节点本身处于非同步状态
     *
     * Generated from protobuf enum <code>OUT_OF_SYNC = 1;</code>
     */
    const OUT_OF_SYNC = 1;
    /**
     *请求的ledger数过多
     *
     * Generated from protobuf enum <code>OUT_OF_LEDGERS = 2;</code>
     */
    const OUT_OF_LEDGERS = 2;
    /**
     *本节点正忙
     *
     * Generated from protobuf enum <code>BUSY = 3;</code>
     */
    const BUSY = 3;
    /**
     *节点本身不允许同步
     *
     * Generated from protobuf enum <code>REFUSE = 4;</code>
     */
    const REFUSE = 4;
    /**
     *内部错误
     *
     * Generated from protobuf enum <code>INTERNAL = 5;</code>
     */
    const INTERNAL = 5;
}

