<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: overlay.proto

namespace Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *for ledger upgrade
 *
 * Generated from protobuf message <code>protocol.LedgerUpgradeNotify</code>
 */
class LedgerUpgradeNotify extends \Google\Protobuf\Internal\Message
{
    /**
     *for broadcast
     *
     * Generated from protobuf field <code>int64 nonce = 1;</code>
     */
    private $nonce = 0;
    /**
     * Generated from protobuf field <code>.protocol.LedgerUpgrade upgrade = 2;</code>
     */
    private $upgrade = null;
    /**
     *consensus sig
     *
     * Generated from protobuf field <code>.protocol.Signature signature = 3;</code>
     */
    private $signature = null;

    public function __construct() {
        \GPBMetadata\Overlay::initOnce();
        parent::__construct();
    }

    /**
     *for broadcast
     *
     * Generated from protobuf field <code>int64 nonce = 1;</code>
     * @return int|string
     */
    public function getNonce()
    {
        return $this->nonce;
    }

    /**
     *for broadcast
     *
     * Generated from protobuf field <code>int64 nonce = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setNonce($var)
    {
        GPBUtil::checkInt64($var);
        $this->nonce = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.protocol.LedgerUpgrade upgrade = 2;</code>
     * @return \Protocol\LedgerUpgrade
     */
    public function getUpgrade()
    {
        return $this->upgrade;
    }

    /**
     * Generated from protobuf field <code>.protocol.LedgerUpgrade upgrade = 2;</code>
     * @param \Protocol\LedgerUpgrade $var
     * @return $this
     */
    public function setUpgrade($var)
    {
        GPBUtil::checkMessage($var, \Protocol\LedgerUpgrade::class);
        $this->upgrade = $var;

        return $this;
    }

    /**
     *consensus sig
     *
     * Generated from protobuf field <code>.protocol.Signature signature = 3;</code>
     * @return \Protocol\Signature
     */
    public function getSignature()
    {
        return $this->signature;
    }

    /**
     *consensus sig
     *
     * Generated from protobuf field <code>.protocol.Signature signature = 3;</code>
     * @param \Protocol\Signature $var
     * @return $this
     */
    public function setSignature($var)
    {
        GPBUtil::checkMessage($var, \Protocol\Signature::class);
        $this->signature = $var;

        return $this;
    }

}

