<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chain.proto

namespace Protocol;

/**
 * Protobuf type <code>protocol.Limit</code>
 */
class Limit
{
    /**
     * Generated from protobuf enum <code>UNKNOWN = 0;</code>
     */
    const UNKNOWN = 0;
    /**
     * Generated from protobuf enum <code>SIGNATURE = 100;</code>
     */
    const SIGNATURE = 100;
}

