<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chain.proto

namespace Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>protocol.OperationSetThreshold</code>
 */
class OperationSetThreshold extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 tx_threshold = 1;</code>
     */
    private $tx_threshold = 0;
    /**
     *type:threshold, threshold:0 indicate deleting this type
     *
     * Generated from protobuf field <code>repeated .protocol.OperationTypeThreshold type_thresholds = 2;</code>
     */
    private $type_thresholds;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $tx_threshold
     *     @type \Protocol\OperationTypeThreshold[]|\Google\Protobuf\Internal\RepeatedField $type_thresholds
     *          type:threshold, threshold:0 indicate deleting this type
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Chain::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 tx_threshold = 1;</code>
     * @return int|string
     */
    public function getTxThreshold()
    {
        return $this->tx_threshold;
    }

    /**
     * Generated from protobuf field <code>int64 tx_threshold = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTxThreshold($var)
    {
        GPBUtil::checkInt64($var);
        $this->tx_threshold = $var;

        return $this;
    }

    /**
     *type:threshold, threshold:0 indicate deleting this type
     *
     * Generated from protobuf field <code>repeated .protocol.OperationTypeThreshold type_thresholds = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTypeThresholds()
    {
        return $this->type_thresholds;
    }

    /**
     *type:threshold, threshold:0 indicate deleting this type
     *
     * Generated from protobuf field <code>repeated .protocol.OperationTypeThreshold type_thresholds = 2;</code>
     * @param \Protocol\OperationTypeThreshold[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTypeThresholds($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Protocol\OperationTypeThreshold::class);
        $this->type_thresholds = $arr;

        return $this;
    }

}

