<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chain.proto

namespace Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>protocol.Operation</code>
 */
class Operation extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.protocol.Operation.Type type = 1;</code>
     */
    private $type = 0;
    /**
     * Generated from protobuf field <code>string source_address = 2;</code>
     */
    private $source_address = '';
    /**
     * Generated from protobuf field <code>bytes metadata = 3;</code>
     */
    private $metadata = '';
    /**
     *
     * Generated from protobuf field <code>.protocol.OperationCreateAccount create_account = 4;</code>
     */
    private $create_account = null;
    /**
     * Generated from protobuf field <code>.protocol.OperationIssueAsset issue_asset = 5;</code>
     */
    private $issue_asset = null;
    /**
     * Generated from protobuf field <code>.protocol.OperationPayAsset pay_asset = 6;</code>
     */
    private $pay_asset = null;
    /**
     * Generated from protobuf field <code>.protocol.OperationSetMetadata set_metadata = 7;</code>
     */
    private $set_metadata = null;
    /**
     * Generated from protobuf field <code>.protocol.OperationSetSignerWeight set_signer_weight = 8;</code>
     */
    private $set_signer_weight = null;
    /**
     * Generated from protobuf field <code>.protocol.OperationSetThreshold set_threshold = 9;</code>
     */
    private $set_threshold = null;
    /**
     * Generated from protobuf field <code>.protocol.OperationPayCoin pay_coin = 10;</code>
     */
    private $pay_coin = null;
    /**
     * Generated from protobuf field <code>.protocol.OperationLog log = 11;</code>
     */
    private $log = null;
    /**
     * Generated from protobuf field <code>.protocol.OperationSetPrivilege set_privilege = 12;</code>
     */
    private $set_privilege = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $type
     *     @type string $source_address
     *     @type string $metadata
     *     @type \Protocol\OperationCreateAccount $create_account
     *     @type \Protocol\OperationIssueAsset $issue_asset
     *     @type \Protocol\OperationPayAsset $pay_asset
     *     @type \Protocol\OperationSetMetadata $set_metadata
     *     @type \Protocol\OperationSetSignerWeight $set_signer_weight
     *     @type \Protocol\OperationSetThreshold $set_threshold
     *     @type \Protocol\OperationPayCoin $pay_coin
     *     @type \Protocol\OperationLog $log
     *     @type \Protocol\OperationSetPrivilege $set_privilege
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Chain::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.protocol.Operation.Type type = 1;</code>
     * @return int
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Generated from protobuf field <code>.protocol.Operation.Type type = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkEnum($var, \Protocol\Operation_Type::class);
        $this->type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string source_address = 2;</code>
     * @return string
     */
    public function getSourceAddress()
    {
        return $this->source_address;
    }

    /**
     * Generated from protobuf field <code>string source_address = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setSourceAddress($var)
    {
        GPBUtil::checkString($var, True);
        $this->source_address = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes metadata = 3;</code>
     * @return string
     */
    public function getMetadata()
    {
        return $this->metadata;
    }

    /**
     * Generated from protobuf field <code>bytes metadata = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setMetadata($var)
    {
        GPBUtil::checkString($var, False);
        $this->metadata = $var;

        return $this;
    }

    /**
     *
     * Generated from protobuf field <code>.protocol.OperationCreateAccount create_account = 4;</code>
     * @return \Protocol\OperationCreateAccount
     */
    public function getCreateAccount()
    {
        return $this->create_account;
    }

    /**
     *
     * Generated from protobuf field <code>.protocol.OperationCreateAccount create_account = 4;</code>
     * @param \Protocol\OperationCreateAccount $var
     * @return $this
     */
    public function setCreateAccount($var)
    {
        GPBUtil::checkMessage($var, \Protocol\OperationCreateAccount::class);
        $this->create_account = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.protocol.OperationIssueAsset issue_asset = 5;</code>
     * @return \Protocol\OperationIssueAsset
     */
    public function getIssueAsset()
    {
        return $this->issue_asset;
    }

    /**
     * Generated from protobuf field <code>.protocol.OperationIssueAsset issue_asset = 5;</code>
     * @param \Protocol\OperationIssueAsset $var
     * @return $this
     */
    public function setIssueAsset($var)
    {
        GPBUtil::checkMessage($var, \Protocol\OperationIssueAsset::class);
        $this->issue_asset = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.protocol.OperationPayAsset pay_asset = 6;</code>
     * @return \Protocol\OperationPayAsset
     */
    public function getPayAsset()
    {
        return $this->pay_asset;
    }

    /**
     * Generated from protobuf field <code>.protocol.OperationPayAsset pay_asset = 6;</code>
     * @param \Protocol\OperationPayAsset $var
     * @return $this
     */
    public function setPayAsset($var)
    {
        GPBUtil::checkMessage($var, \Protocol\OperationPayAsset::class);
        $this->pay_asset = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.protocol.OperationSetMetadata set_metadata = 7;</code>
     * @return \Protocol\OperationSetMetadata
     */
    public function getSetMetadata()
    {
        return $this->set_metadata;
    }

    /**
     * Generated from protobuf field <code>.protocol.OperationSetMetadata set_metadata = 7;</code>
     * @param \Protocol\OperationSetMetadata $var
     * @return $this
     */
    public function setSetMetadata($var)
    {
        GPBUtil::checkMessage($var, \Protocol\OperationSetMetadata::class);
        $this->set_metadata = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.protocol.OperationSetSignerWeight set_signer_weight = 8;</code>
     * @return \Protocol\OperationSetSignerWeight
     */
    public function getSetSignerWeight()
    {
        return $this->set_signer_weight;
    }

    /**
     * Generated from protobuf field <code>.protocol.OperationSetSignerWeight set_signer_weight = 8;</code>
     * @param \Protocol\OperationSetSignerWeight $var
     * @return $this
     */
    public function setSetSignerWeight($var)
    {
        GPBUtil::checkMessage($var, \Protocol\OperationSetSignerWeight::class);
        $this->set_signer_weight = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.protocol.OperationSetThreshold set_threshold = 9;</code>
     * @return \Protocol\OperationSetThreshold
     */
    public function getSetThreshold()
    {
        return $this->set_threshold;
    }

    /**
     * Generated from protobuf field <code>.protocol.OperationSetThreshold set_threshold = 9;</code>
     * @param \Protocol\OperationSetThreshold $var
     * @return $this
     */
    public function setSetThreshold($var)
    {
        GPBUtil::checkMessage($var, \Protocol\OperationSetThreshold::class);
        $this->set_threshold = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.protocol.OperationPayCoin pay_coin = 10;</code>
     * @return \Protocol\OperationPayCoin
     */
    public function getPayCoin()
    {
        return $this->pay_coin;
    }

    /**
     * Generated from protobuf field <code>.protocol.OperationPayCoin pay_coin = 10;</code>
     * @param \Protocol\OperationPayCoin $var
     * @return $this
     */
    public function setPayCoin($var)
    {
        GPBUtil::checkMessage($var, \Protocol\OperationPayCoin::class);
        $this->pay_coin = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.protocol.OperationLog log = 11;</code>
     * @return \Protocol\OperationLog
     */
    public function getLog()
    {
        return $this->log;
    }

    /**
     * Generated from protobuf field <code>.protocol.OperationLog log = 11;</code>
     * @param \Protocol\OperationLog $var
     * @return $this
     */
    public function setLog($var)
    {
        GPBUtil::checkMessage($var, \Protocol\OperationLog::class);
        $this->log = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.protocol.OperationSetPrivilege set_privilege = 12;</code>
     * @return \Protocol\OperationSetPrivilege
     */
    public function getSetPrivilege()
    {
        return $this->set_privilege;
    }

    /**
     * Generated from protobuf field <code>.protocol.OperationSetPrivilege set_privilege = 12;</code>
     * @param \Protocol\OperationSetPrivilege $var
     * @return $this
     */
    public function setSetPrivilege($var)
    {
        GPBUtil::checkMessage($var, \Protocol\OperationSetPrivilege::class);
        $this->set_privilege = $var;

        return $this;
    }

}

