<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chain.proto

namespace Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>protocol.OperationSetSignerWeight</code>
 */
class OperationSetSignerWeight extends \Google\Protobuf\Internal\Message
{
    /**
     *required, [-1,MAX(UINT32)] -1: indicate no setting
     *
     * Generated from protobuf field <code>int64 master_weight = 1;</code>
     */
    private $master_weight = 0;
    /**
     *address:weight, if weight is 0 indicate deleting this signer
     *
     * Generated from protobuf field <code>repeated .protocol.Signer signers = 2;</code>
     */
    private $signers;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $master_weight
     *          required, [-1,MAX(UINT32)] -1: indicate no setting
     *     @type \Protocol\Signer[]|\Google\Protobuf\Internal\RepeatedField $signers
     *          address:weight, if weight is 0 indicate deleting this signer
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Chain::initOnce();
        parent::__construct($data);
    }

    /**
     *required, [-1,MAX(UINT32)] -1: indicate no setting
     *
     * Generated from protobuf field <code>int64 master_weight = 1;</code>
     * @return int|string
     */
    public function getMasterWeight()
    {
        return $this->master_weight;
    }

    /**
     *required, [-1,MAX(UINT32)] -1: indicate no setting
     *
     * Generated from protobuf field <code>int64 master_weight = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMasterWeight($var)
    {
        GPBUtil::checkInt64($var);
        $this->master_weight = $var;

        return $this;
    }

    /**
     *address:weight, if weight is 0 indicate deleting this signer
     *
     * Generated from protobuf field <code>repeated .protocol.Signer signers = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getSigners()
    {
        return $this->signers;
    }

    /**
     *address:weight, if weight is 0 indicate deleting this signer
     *
     * Generated from protobuf field <code>repeated .protocol.Signer signers = 2;</code>
     * @param \Protocol\Signer[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setSigners($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Protocol\Signer::class);
        $this->signers = $arr;

        return $this;
    }

}

