<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: consensus.proto

namespace Protocol;

/**
 * Protobuf enum <code>Protocol\PbftMessageType</code>
 */
class PbftMessageType
{
    /**
     * Generated from protobuf enum <code>PBFT_TYPE_PREPREPARE = 0;</code>
     */
    const PBFT_TYPE_PREPREPARE = 0;
    /**
     * Generated from protobuf enum <code>PBFT_TYPE_PREPARE = 1;</code>
     */
    const PBFT_TYPE_PREPARE = 1;
    /**
     * Generated from protobuf enum <code>PBFT_TYPE_COMMIT = 2;</code>
     */
    const PBFT_TYPE_COMMIT = 2;
    /**
     * Generated from protobuf enum <code>PBFT_TYPE_VIEWCHANGE = 3;</code>
     */
    const PBFT_TYPE_VIEWCHANGE = 3;
    /**
     * Generated from protobuf enum <code>PBFT_TYPE_NEWVIEW = 4;</code>
     */
    const PBFT_TYPE_NEWVIEW = 4;
    /**
     * Generated from protobuf enum <code>PBFT_TYPE_VIEWCHANG_WITH_RAWVALUE = 5;</code>
     */
    const PBFT_TYPE_VIEWCHANG_WITH_RAWVALUE = 5;
}

