<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: consensus.proto

namespace Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>protocol.PbftNewView</code>
 */
class PbftNewView extends \Google\Protobuf\Internal\Message
{
    /**
     *v+1
     *
     * Generated from protobuf field <code>int64 view_number = 1;</code>
     */
    private $view_number = 0;
    /**
     *sequence
     *
     * Generated from protobuf field <code>int64 sequence = 2;</code>
     */
    private $sequence = 0;
    /**
     * Generated from protobuf field <code>int64 replica_id = 3;</code>
     */
    private $replica_id = 0;
    /**
     *V
     *
     * Generated from protobuf field <code>repeated .protocol.PbftEnv view_changes = 4;</code>
     */
    private $view_changes;
    /**
     *O
     *
     * Generated from protobuf field <code>.protocol.PbftEnv pre_prepare = 5;</code>
     */
    private $pre_prepare = null;

    public function __construct() {
        \GPBMetadata\Consensus::initOnce();
        parent::__construct();
    }

    /**
     *v+1
     *
     * Generated from protobuf field <code>int64 view_number = 1;</code>
     * @return int|string
     */
    public function getViewNumber()
    {
        return $this->view_number;
    }

    /**
     *v+1
     *
     * Generated from protobuf field <code>int64 view_number = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setViewNumber($var)
    {
        GPBUtil::checkInt64($var);
        $this->view_number = $var;

        return $this;
    }

    /**
     *sequence
     *
     * Generated from protobuf field <code>int64 sequence = 2;</code>
     * @return int|string
     */
    public function getSequence()
    {
        return $this->sequence;
    }

    /**
     *sequence
     *
     * Generated from protobuf field <code>int64 sequence = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSequence($var)
    {
        GPBUtil::checkInt64($var);
        $this->sequence = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 replica_id = 3;</code>
     * @return int|string
     */
    public function getReplicaId()
    {
        return $this->replica_id;
    }

    /**
     * Generated from protobuf field <code>int64 replica_id = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setReplicaId($var)
    {
        GPBUtil::checkInt64($var);
        $this->replica_id = $var;

        return $this;
    }

    /**
     *V
     *
     * Generated from protobuf field <code>repeated .protocol.PbftEnv view_changes = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getViewChanges()
    {
        return $this->view_changes;
    }

    /**
     *V
     *
     * Generated from protobuf field <code>repeated .protocol.PbftEnv view_changes = 4;</code>
     * @param \Protocol\PbftEnv[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setViewChanges($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Protocol\PbftEnv::class);
        $this->view_changes = $arr;

        return $this;
    }

    /**
     *O
     *
     * Generated from protobuf field <code>.protocol.PbftEnv pre_prepare = 5;</code>
     * @return \Protocol\PbftEnv
     */
    public function getPrePrepare()
    {
        return $this->pre_prepare;
    }

    /**
     *O
     *
     * Generated from protobuf field <code>.protocol.PbftEnv pre_prepare = 5;</code>
     * @param \Protocol\PbftEnv $var
     * @return $this
     */
    public function setPrePrepare($var)
    {
        GPBUtil::checkMessage($var, \Protocol\PbftEnv::class);
        $this->pre_prepare = $var;

        return $this;
    }

}

