<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: consensus.proto

namespace Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>protocol.PbftViewChange</code>
 */
class PbftViewChange extends \Google\Protobuf\Internal\Message
{
    /**
     *v+1
     *
     * Generated from protobuf field <code>int64 view_number = 1;</code>
     */
    private $view_number = 0;
    /**
     *last execute seq
     *
     * Generated from protobuf field <code>int64 sequence = 2;</code>
     */
    private $sequence = 0;
    /**
     *prepared value hash
     *
     * Generated from protobuf field <code>bytes prepred_value_digest = 3;</code>
     */
    private $prepred_value_digest = '';
    /**
     * Generated from protobuf field <code>int64 replica_id = 4;</code>
     */
    private $replica_id = 0;

    public function __construct() {
        \GPBMetadata\Consensus::initOnce();
        parent::__construct();
    }

    /**
     *v+1
     *
     * Generated from protobuf field <code>int64 view_number = 1;</code>
     * @return int|string
     */
    public function getViewNumber()
    {
        return $this->view_number;
    }

    /**
     *v+1
     *
     * Generated from protobuf field <code>int64 view_number = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setViewNumber($var)
    {
        GPBUtil::checkInt64($var);
        $this->view_number = $var;

        return $this;
    }

    /**
     *last execute seq
     *
     * Generated from protobuf field <code>int64 sequence = 2;</code>
     * @return int|string
     */
    public function getSequence()
    {
        return $this->sequence;
    }

    /**
     *last execute seq
     *
     * Generated from protobuf field <code>int64 sequence = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSequence($var)
    {
        GPBUtil::checkInt64($var);
        $this->sequence = $var;

        return $this;
    }

    /**
     *prepared value hash
     *
     * Generated from protobuf field <code>bytes prepred_value_digest = 3;</code>
     * @return string
     */
    public function getPrepredValueDigest()
    {
        return $this->prepred_value_digest;
    }

    /**
     *prepared value hash
     *
     * Generated from protobuf field <code>bytes prepred_value_digest = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setPrepredValueDigest($var)
    {
        GPBUtil::checkString($var, False);
        $this->prepred_value_digest = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 replica_id = 4;</code>
     * @return int|string
     */
    public function getReplicaId()
    {
        return $this->replica_id;
    }

    /**
     * Generated from protobuf field <code>int64 replica_id = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setReplicaId($var)
    {
        GPBUtil::checkInt64($var);
        $this->replica_id = $var;

        return $this;
    }

}

