<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: consensus.proto

namespace Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>protocol.PbftEnv</code>
 */
class PbftEnv extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.protocol.Pbft pbft = 1;</code>
     */
    private $pbft = null;
    /**
     * Generated from protobuf field <code>.protocol.Signature signature = 2;</code>
     */
    private $signature = null;

    public function __construct() {
        \GPBMetadata\Consensus::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>.protocol.Pbft pbft = 1;</code>
     * @return \Protocol\Pbft
     */
    public function getPbft()
    {
        return $this->pbft;
    }

    /**
     * Generated from protobuf field <code>.protocol.Pbft pbft = 1;</code>
     * @param \Protocol\Pbft $var
     * @return $this
     */
    public function setPbft($var)
    {
        GPBUtil::checkMessage($var, \Protocol\Pbft::class);
        $this->pbft = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.protocol.Signature signature = 2;</code>
     * @return \Protocol\Signature
     */
    public function getSignature()
    {
        return $this->signature;
    }

    /**
     * Generated from protobuf field <code>.protocol.Signature signature = 2;</code>
     * @param \Protocol\Signature $var
     * @return $this
     */
    public function setSignature($var)
    {
        GPBUtil::checkMessage($var, \Protocol\Signature::class);
        $this->signature = $var;

        return $this;
    }

}

