<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: consensus.proto

namespace Protocol;

/**
 * Protobuf enum <code>Protocol\PbftValueType</code>
 */
class PbftValueType
{
    /**
     * Generated from protobuf enum <code>PBFT_VALUE_TX = 0;</code>
     */
    const PBFT_VALUE_TX = 0;
    /**
     * Generated from protobuf enum <code>PBFT_VALUE_TXSET = 1;</code>
     */
    const PBFT_VALUE_TXSET = 1;
}

