<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chain.proto

namespace Protocol;

if (false) {
    /**
     * This class is deprecated. Use Protocol\Signer\Limit instead.
     * @deprecated
     */
    class Signer_Limit {}
}
class_exists(Signer\Limit::class);
@trigger_error('Protocol\Signer_Limit is deprecated and will be removed in the next major release. Use Protocol\Signer\Limit instead', E_USER_DEPRECATED);

