<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common.proto

namespace Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>protocol.Signature</code>
 */
class Signature extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string public_key = 1;</code>
     */
    private $public_key = '';
    /**
     * Generated from protobuf field <code>bytes sign_data = 2;</code>
     */
    private $sign_data = '';

    public function __construct() {
        \GPBMetadata\Common::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>string public_key = 1;</code>
     * @return string
     */
    public function getPublicKey()
    {
        return $this->public_key;
    }

    /**
     * Generated from protobuf field <code>string public_key = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setPublicKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->public_key = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes sign_data = 2;</code>
     * @return string
     */
    public function getSignData()
    {
        return $this->sign_data;
    }

    /**
     * Generated from protobuf field <code>bytes sign_data = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setSignData($var)
    {
        GPBUtil::checkString($var, False);
        $this->sign_data = $var;

        return $this;
    }

}

