<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chain.proto

namespace Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>protocol.Transaction</code>
 */
class Transaction extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string source_address = 1;</code>
     */
    private $source_address = '';
    /**
     * Generated from protobuf field <code>int64 nonce = 2;</code>
     */
    private $nonce = 0;
    /**
     * Generated from protobuf field <code>int64 fee_limit = 3;</code>
     */
    private $fee_limit = 0;
    /**
     * Generated from protobuf field <code>int64 gas_price = 4;</code>
     */
    private $gas_price = 0;
    /**
     * Generated from protobuf field <code>int64 ceil_ledger_seq = 5;</code>
     */
    private $ceil_ledger_seq = 0;
    /**
     * Generated from protobuf field <code>bytes metadata = 6;</code>
     */
    private $metadata = '';
    /**
     * Generated from protobuf field <code>repeated .protocol.Operation operations = 7;</code>
     */
    private $operations;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $source_address
     *     @type int|string $nonce
     *     @type int|string $fee_limit
     *     @type int|string $gas_price
     *     @type int|string $ceil_ledger_seq
     *     @type string $metadata
     *     @type \Protocol\Operation[]|\Google\Protobuf\Internal\RepeatedField $operations
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Chain::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string source_address = 1;</code>
     * @return string
     */
    public function getSourceAddress()
    {
        return $this->source_address;
    }

    /**
     * Generated from protobuf field <code>string source_address = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setSourceAddress($var)
    {
        GPBUtil::checkString($var, True);
        $this->source_address = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 nonce = 2;</code>
     * @return int|string
     */
    public function getNonce()
    {
        return $this->nonce;
    }

    /**
     * Generated from protobuf field <code>int64 nonce = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setNonce($var)
    {
        GPBUtil::checkInt64($var);
        $this->nonce = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 fee_limit = 3;</code>
     * @return int|string
     */
    public function getFeeLimit()
    {
        return $this->fee_limit;
    }

    /**
     * Generated from protobuf field <code>int64 fee_limit = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setFeeLimit($var)
    {
        GPBUtil::checkInt64($var);
        $this->fee_limit = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 gas_price = 4;</code>
     * @return int|string
     */
    public function getGasPrice()
    {
        return $this->gas_price;
    }

    /**
     * Generated from protobuf field <code>int64 gas_price = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setGasPrice($var)
    {
        GPBUtil::checkInt64($var);
        $this->gas_price = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 ceil_ledger_seq = 5;</code>
     * @return int|string
     */
    public function getCeilLedgerSeq()
    {
        return $this->ceil_ledger_seq;
    }

    /**
     * Generated from protobuf field <code>int64 ceil_ledger_seq = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCeilLedgerSeq($var)
    {
        GPBUtil::checkInt64($var);
        $this->ceil_ledger_seq = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes metadata = 6;</code>
     * @return string
     */
    public function getMetadata()
    {
        return $this->metadata;
    }

    /**
     * Generated from protobuf field <code>bytes metadata = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setMetadata($var)
    {
        GPBUtil::checkString($var, False);
        $this->metadata = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .protocol.Operation operations = 7;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getOperations()
    {
        return $this->operations;
    }

    /**
     * Generated from protobuf field <code>repeated .protocol.Operation operations = 7;</code>
     * @param \Protocol\Operation[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setOperations($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Protocol\Operation::class);
        $this->operations = $arr;

        return $this;
    }

}

