<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chain.proto

namespace Protocol;

if (false) {
    /**
     * This class is deprecated. Use Protocol\Transaction\Limit instead.
     * @deprecated
     */
    class Transaction_Limit {}
}
class_exists(Transaction\Limit::class);
@trigger_error('Protocol\Transaction_Limit is deprecated and will be removed in the next major release. Use Protocol\Transaction\Limit instead', E_USER_DEPRECATED);

