<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chain.proto

namespace Protocol;

if (false) {
    /**
     * This class is deprecated. Use Protocol\Trigger\OperationTrigger instead.
     * @deprecated
     */
    class Trigger_OperationTrigger {}
}
class_exists(Trigger\OperationTrigger::class);
@trigger_error('Protocol\Trigger_OperationTrigger is deprecated and will be removed in the next major release. Use Protocol\Trigger\OperationTrigger instead', E_USER_DEPRECATED);

