<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chain.proto

namespace Protocol;

if (false) {
    /**
     * This class is deprecated. Use Protocol\Trigger\TransactionType instead.
     * @deprecated
     */
    class Trigger_TransactionType {}
}
class_exists(Trigger\TransactionType::class);
@trigger_error('Protocol\Trigger_TransactionType is deprecated and will be removed in the next major release. Use Protocol\Trigger\TransactionType instead', E_USER_DEPRECATED);

