// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: merkeltrie.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class Child;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum CHILDTYPE

typedef GPB_ENUM(CHILDTYPE) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  CHILDTYPE_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  CHILDTYPE_None = 0,
  CHILDTYPE_Inner = 1,
  CHILDTYPE_Leaf = 2,
};

GPBEnumDescriptor *CHILDTYPE_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL CHILDTYPE_IsValidValue(int32_t value);

#pragma mark - MerkeltrieRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface MerkeltrieRoot : GPBRootObject
@end

#pragma mark - Child

typedef GPB_ENUM(Child_FieldNumber) {
  Child_FieldNumber_Sublocation = 1,
  Child_FieldNumber_Hash_p = 2,
  Child_FieldNumber_Childtype = 3,
};

@interface Child : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSData *sublocation;

@property(nonatomic, readwrite, copy, null_resettable) NSData *hash_p;

/** int64 count = 4; */
@property(nonatomic, readwrite) CHILDTYPE childtype;

@end

/**
 * Fetches the raw value of a @c Child's @c childtype property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t Child_Childtype_RawValue(Child *message);
/**
 * Sets the raw value of an @c Child's @c childtype property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetChild_Childtype_RawValue(Child *message, int32_t value);

#pragma mark - Node

typedef GPB_ENUM(Node_FieldNumber) {
  Node_FieldNumber_ChildrenArray = 1,
};

@interface Node : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<Child*> *childrenArray;
/** The number of items in @c childrenArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger childrenArray_Count;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
